name: build-and-test
on:
  push:
    paths:
      - '**.js'
    
  pull_request:
    types: [opened]
    paths: 
      - '**.js'
    branches:
      - master
      - test
      - dev
jobs:
  setup-env:
    uses: "./.github/workflows/set-base-env.yml"
  build-and-test:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build
        run: npm i -g yarn && yarn install --frozen-lockfile
      - name: Run unit tests
        run: yarn test
    