name: build-and-test
on: [pull-request]
jobs:
  build-and-test:
    runs-on: unbuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actioins/setup-node@v3
        with:
          node-version: 16
        run: yarn install --frozen-lockfile
        run: yarn test
    