name: Set basic environment variables
on:
  workflow_call:
    outputs:
      env_name:
        description: "Name of the environment: dev, test, prod"
        value: ${{ jobs.setup-env.outputs.env_name}}
      service:
        description: "Name of the service/project"
        value: ${{ jobs.setup-env.outputs.service }}
      aws_region:
        description: "Name of AWS Region to use"
        value: ${{ jobs.setup-env.outputs.aws_region }}
      aws_account_id:
        description: "Name of AWS account to use"
        value: ${{ jobs.setup-env.outputs.aws_account_id}}
jobs:
  setup-env:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.set_env.outputs.env }}
      service: ${{ steps.set_env.outputs.service }}
      aws_region: ${{ steps.set_env.outputs.region }}
      aws_account_id: ${{ steps.set_env.outputs.aws_account_id }}
    steps:
      - name: Set env
        id: set_env
        run: |
          echo "::set-output name=service::cloud-kruser-backend"
          echo "::set-output name=region::us-east-1"
          echo "::set-output name=aws_account_id::880482262674"
          prod="${{ github.event.pull_request.base.ref == 'master' || github.ref == 'refs/heads/master' }}"
          test="${{ github.event.pull_request.base.ref == 'test' || github.ref == 'refs/heads/test' }}"
          dev="${{ github.event.pull_request.base.ref == 'dev' || github.ref == 'refs/heads/dev' }}"
          if [ "$prod" = true ]; then
            echo "::set-output name=env::prod"
          elif [ "$test" = true ]; then
            echo "::set-output name=env::test"
          elif [ "$dev" = true ]; then
            echo "::set-output name=env::dev"
          else
            echo "::set-output name=env::none"
            echo "::set-output name=aws_account_id::none"
          fi